apiVersion: v1
kind: Pod
metadata:
  name: task1
  labels:
    app: task1-app
spec:
  containers:
  - name: task1
    image: pixcs13/task1jenk:latest 
    ports: 
    - containerPort: 5500
    env:
    - name: YOUR_NAME
      value: QA-Kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: task1-app
spec:
  type: ClusterIP
  selector:
    app: task1-app
  ports:
  - protocol: TCP
    port: 5500